// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VaalBeachClub.Data;
using VaalBeachClub.Models.Domain.Addresses;

namespace VaalBeachClub.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20190524181849_10")]
    partial class _10
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("VaalBeachClub.Models.Domain.Addresses.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("AddressID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AddressType");

                    b.Property<string>("AreaCode");

                    b.Property<int>("BeachClubMemberID")
                        .HasColumnName("BeachClubMemberID");

                    b.Property<string>("City");

                    b.Property<int>("CountryID");

                    b.Property<bool>("IsPrimaryAddress");

                    b.Property<string>("Suburb");

                    b.HasKey("Id");

                    b.HasIndex("BeachClubMemberID");

                    b.HasIndex("CountryID");

                    b.ToTable("Addresses");

                    b.HasDiscriminator<int>("AddressType");
                });

            modelBuilder.Entity("VaalBeachClub.Models.Domain.BoatHouses.BoatHouse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("BoatHouseID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BoatHouseNumber")
                        .HasColumnName("BoatHouseNumber")
                        .HasMaxLength(250);

                    b.Property<int>("BoatHouseSizeID");

                    b.HasKey("Id");

                    b.HasIndex("BoatHouseSizeID");

                    b.ToTable("BoatHouses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BoatHouseNumber = "BH001",
                            BoatHouseSizeID = 1
                        },
                        new
                        {
                            Id = 2,
                            BoatHouseNumber = "BH002",
                            BoatHouseSizeID = 2
                        },
                        new
                        {
                            Id = 3,
                            BoatHouseNumber = "BH003",
                            BoatHouseSizeID = 3
                        },
                        new
                        {
                            Id = 4,
                            BoatHouseNumber = "BH004",
                            BoatHouseSizeID = 4
                        },
                        new
                        {
                            Id = 5,
                            BoatHouseNumber = "BH005",
                            BoatHouseSizeID = 5
                        },
                        new
                        {
                            Id = 6,
                            BoatHouseNumber = "BH006",
                            BoatHouseSizeID = 6
                        });
                });

            modelBuilder.Entity("VaalBeachClub.Models.Domain.BoatHouses.BoatHouseSize", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("BoatHouseSizeID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Cost")
                        .HasColumnType("money");

                    b.Property<string>("Description");

                    b.Property<decimal>("Hieght")
                        .HasColumnType("numeric(18, 1)");

                    b.Property<decimal>("Length")
                        .HasColumnType("numeric(18, 1)");

                    b.Property<decimal>("Width")
                        .HasColumnType("numeric(18, 1)");

                    b.HasKey("Id");

                    b.ToTable("BoatHouseSizes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cost = 14380m,
                            Description = "Boat Size A",
                            Hieght = 2.5m,
                            Length = 8m,
                            Width = 3m
                        },
                        new
                        {
                            Id = 2,
                            Cost = 16392m,
                            Description = "Boat Size B",
                            Hieght = 2.8m,
                            Length = 9m,
                            Width = 3.5m
                        },
                        new
                        {
                            Id = 3,
                            Cost = 16392m,
                            Description = "Boat Size C",
                            Hieght = 3.5m,
                            Length = 9m,
                            Width = 3.5m
                        },
                        new
                        {
                            Id = 4,
                            Cost = 18117m,
                            Description = "Boat Size D",
                            Hieght = 4m,
                            Length = 10m,
                            Width = 3.5m
                        },
                        new
                        {
                            Id = 5,
                            Cost = 20340m,
                            Description = "Boat Size E",
                            Hieght = 2.8m,
                            Length = 12m,
                            Width = 3.5m
                        },
                        new
                        {
                            Id = 6,
                            Cost = 20340m,
                            Description = "Boat Size F",
                            Hieght = 3.5m,
                            Length = 12m,
                            Width = 3.5m
                        });
                });

            modelBuilder.Entity("VaalBeachClub.Models.Domain.Bookings.CampSiteBooking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("CampSiteBookingID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BeachClubMemberID");

                    b.Property<int>("CampSiteID");

                    b.Property<DateTime>("EndDateTime");

                    b.Property<DateTime>("StartDateTime");

                    b.HasKey("Id");

                    b.HasIndex("BeachClubMemberID");

                    b.HasIndex("CampSiteID");

                    b.ToTable("CampSiteBookings");
                });

            modelBuilder.Entity("VaalBeachClub.Models.Domain.CampSites.CampSite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("CampSiteID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CampSiteNumber");

                    b.Property<bool>("hasElectricity");

                    b.HasKey("Id");

                    b.ToTable("CampSite");
                });

            modelBuilder.Entity("VaalBeachClub.Models.Domain.Common.ContactDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ContactDetailID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BeachClubMemberID");

                    b.Property<int>("ContactDetailTypeID");

                    b.Property<string>("ContactDetailValue")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false);

                    b.HasKey("Id");

                    b.HasIndex("BeachClubMemberID");

                    b.HasIndex("ContactDetailTypeID");

                    b.ToTable("ContactDetails");
                });

            modelBuilder.Entity("VaalBeachClub.Models.Domain.Common.ContactDetailType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ContactDetailTypeID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ContactDetailTypeValue")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false);

                    b.HasKey("Id");

                    b.ToTable("ContactDetailTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ContactDetailTypeValue = "Email Address"
                        },
                        new
                        {
                            Id = 2,
                            ContactDetailTypeValue = "Cell Number"
                        },
                        new
                        {
                            Id = 3,
                            ContactDetailTypeValue = "Office Number"
                        },
                        new
                        {
                            Id = 4,
                            ContactDetailTypeValue = "Home Number"
                        });
                });

            modelBuilder.Entity("VaalBeachClub.Models.Domain.Common.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("CountryID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .IsUnicode(false);

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasMaxLength(75)
                        .IsUnicode(false);

                    b.HasKey("Id");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("VaalBeachClub.Models.Domain.Fees.BeachClubFeeStructure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("BeachClubFeeStructureID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("CampSitePerNight")
                        .HasColumnType("Money");

                    b.Property<decimal>("CampSitePerPersonForMembers")
                        .HasColumnType("Money");

                    b.Property<decimal>("CampSitePerPersonForNonMembers")
                        .HasColumnType("Money");

                    b.Property<decimal>("MemberEntranceFee")
                        .HasColumnType("Money");

                    b.Property<decimal>("NonMemberBoatEntranceFee")
                        .HasColumnType("Money");

                    b.Property<decimal>("NonMemberEntranceFee")
                        .HasColumnType("Money");

                    b.Property<decimal>("NonMemberJetSkiEntranceFee")
                        .HasColumnType("Money");

                    b.Property<decimal>("NonMemberVehicleEntranceFee")
                        .HasColumnType("Money");

                    b.HasKey("Id");

                    b.ToTable("BeachClubFeeStructures");
                });

            modelBuilder.Entity("VaalBeachClub.Models.Domain.Fees.BoatHouseCommissionFee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("CommissionFeeID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BoatHouseSizeID");

                    b.Property<decimal>("CommisionPercentage")
                        .HasColumnType("Decimal(18,2)");

                    b.Property<DateTime>("DateLastUpdated");

                    b.Property<bool>("IsCurrentRate");

                    b.HasKey("Id");

                    b.HasIndex("BoatHouseSizeID");

                    b.ToTable("BoatHouseCommissionFees");
                });

            modelBuilder.Entity("VaalBeachClub.Models.Domain.Fees.EntranceCommissionFee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("CommissionFeeID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BeachClubFeeStructureID");

                    b.Property<decimal>("CommisionPercentage")
                        .HasColumnType("Decimal(18,2)");

                    b.Property<DateTime>("DateLastUpdated");

                    b.Property<bool>("IsCurrentRate");

                    b.HasKey("Id");

                    b.HasIndex("BeachClubFeeStructureID");

                    b.ToTable("EntranceCommissionFee");
                });

            modelBuilder.Entity("VaalBeachClub.Models.Domain.Files.File", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("FileID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(75)
                        .IsUnicode(false);

                    b.Property<string>("FileExtension")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false);

                    b.Property<byte[]>("Image")
                        .HasColumnType("image");

                    b.HasKey("Id");

                    b.ToTable("Files");
                });

            modelBuilder.Entity("VaalBeachClub.Models.Domain.Items.ItemProperty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ItemPropertyID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ItemPropertyDataTypeID");

                    b.Property<string>("Property")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.HasKey("Id");

                    b.HasIndex("ItemPropertyDataTypeID");

                    b.ToTable("ItemProperties");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ItemPropertyDataTypeID = 1,
                            Property = "Colour"
                        },
                        new
                        {
                            Id = 2,
                            ItemPropertyDataTypeID = 1,
                            Property = "Make"
                        },
                        new
                        {
                            Id = 3,
                            ItemPropertyDataTypeID = 1,
                            Property = "Boat Name"
                        },
                        new
                        {
                            Id = 4,
                            ItemPropertyDataTypeID = 2,
                            Property = "Length"
                        },
                        new
                        {
                            Id = 5,
                            ItemPropertyDataTypeID = 2,
                            Property = "Height"
                        },
                        new
                        {
                            Id = 6,
                            ItemPropertyDataTypeID = 1,
                            Property = "Registration Number"
                        },
                        new
                        {
                            Id = 7,
                            ItemPropertyDataTypeID = 1,
                            Property = "Model"
                        },
                        new
                        {
                            Id = 8,
                            ItemPropertyDataTypeID = 1,
                            Property = "Make Of Engine"
                        },
                        new
                        {
                            Id = 9,
                            ItemPropertyDataTypeID = 1,
                            Property = "Width"
                        });
                });

            modelBuilder.Entity("VaalBeachClub.Models.Domain.Items.ItemPropertyDataType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ItemPropertyDataTypeID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ItemPropertyDataTypeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.HasKey("Id");

                    b.ToTable("ItemPropertyDataTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ItemPropertyDataTypeName = "TEXT"
                        },
                        new
                        {
                            Id = 2,
                            ItemPropertyDataTypeName = "NUMERIC"
                        });
                });

            modelBuilder.Entity("VaalBeachClub.Models.Domain.Items.ItemType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ItemTypeID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsOnSiteStorageItem");

                    b.Property<string>("Item")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.HasKey("Id");

                    b.ToTable("ItemTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsOnSiteStorageItem = false,
                            Item = "Trailer"
                        },
                        new
                        {
                            Id = 2,
                            IsOnSiteStorageItem = false,
                            Item = "Boat"
                        },
                        new
                        {
                            Id = 3,
                            IsOnSiteStorageItem = false,
                            Item = "JetSki"
                        },
                        new
                        {
                            Id = 4,
                            IsOnSiteStorageItem = false,
                            Item = "Vechicle"
                        },
                        new
                        {
                            Id = 5,
                            IsOnSiteStorageItem = false,
                            Item = "Wake Board Tower"
                        });
                });

            modelBuilder.Entity("VaalBeachClub.Models.Domain.Items.ItemTypeHierarchy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ItemTypeHierarchyID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ChildID");

                    b.Property<bool>("OccupiesSameSpaceAsParent");

                    b.Property<int>("ParentID");

                    b.HasKey("Id");

                    b.HasIndex("ParentID");

                    b.ToTable("ItemTypeHierarchy");
                });

            modelBuilder.Entity("VaalBeachClub.Models.Domain.Items.ItemTypeProperty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ItemTypePropertyID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ItemID");

                    b.Property<int>("ItemPropertyID");

                    b.Property<bool>("ItemPropertyRequired");

                    b.HasKey("Id");

                    b.HasIndex("ItemID");

                    b.HasIndex("ItemPropertyID");

                    b.ToTable("ItemTypeProperties");
                });

            modelBuilder.Entity("VaalBeachClub.Models.Domain.Logging.ActivityLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ActivityLogTypeId");

                    b.Property<int?>("BeachClubMemberId");

                    b.Property<string>("Comment");

                    b.Property<DateTime>("CreatedOnUtc");

                    b.Property<int>("CustomerId");

                    b.Property<int?>("EntityId");

                    b.Property<string>("EntityName");

                    b.Property<string>("IpAddress");

                    b.HasKey("Id");

                    b.HasIndex("ActivityLogTypeId");

                    b.HasIndex("BeachClubMemberId");

                    b.ToTable("ActivityLogs");
                });

            modelBuilder.Entity("VaalBeachClub.Models.Domain.Logging.ActivityLogType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Enabled");

                    b.Property<string>("Name");

                    b.Property<string>("SystemKeyword");

                    b.HasKey("Id");

                    b.ToTable("ActivityLogTypes");
                });

            modelBuilder.Entity("VaalBeachClub.Models.Domain.Logging.Log", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedOnUtc");

                    b.Property<string>("FullMessage");

                    b.Property<string>("IpAddress");

                    b.Property<int>("LogLevel");

                    b.Property<int>("LogLevelId");

                    b.Property<int?>("MemberId");

                    b.Property<string>("PageUrl");

                    b.Property<string>("ReferrerUrl");

                    b.Property<string>("ShortMessage");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("VaalBeachClub.Models.Domain.Members.AffiliatedMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("AffiliatedMemberID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AffiliatedMemberTypeID");

                    b.Property<int>("BeachClubMemberID");

                    b.Property<DateTime>("DateOfBirth");

                    b.Property<string>("FirstName")
                        .HasMaxLength(75);

                    b.Property<string>("LastName")
                        .HasMaxLength(75);

                    b.HasKey("Id");

                    b.HasIndex("AffiliatedMemberTypeID");

                    b.HasIndex("BeachClubMemberID");

                    b.ToTable("AffiliatedMembers");
                });

            modelBuilder.Entity("VaalBeachClub.Models.Domain.Members.AffiliatedMemberType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("AffiliatedMemberTypeID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AffiliatedMemberTypeName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false);

                    b.HasKey("Id");

                    b.ToTable("AffiliatedMemberTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AffiliatedMemberTypeName = "Wife"
                        },
                        new
                        {
                            Id = 2,
                            AffiliatedMemberTypeName = "Husband"
                        },
                        new
                        {
                            Id = 3,
                            AffiliatedMemberTypeName = "Son"
                        },
                        new
                        {
                            Id = 4,
                            AffiliatedMemberTypeName = "Daughter"
                        },
                        new
                        {
                            Id = 5,
                            AffiliatedMemberTypeName = "Visitor"
                        });
                });

            modelBuilder.Entity("VaalBeachClub.Models.Domain.Members.MemberItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("MemberItemID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BeachClubMemberID");

                    b.Property<bool>("IsOnSite");

                    b.Property<int>("ItemID");

                    b.HasKey("Id");

                    b.HasIndex("BeachClubMemberID");

                    b.HasIndex("ItemID");

                    b.ToTable("MemberItems");
                });

            modelBuilder.Entity("VaalBeachClub.Models.Domain.Members.MemberItemInStorage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("MemberItemInStorageID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BoatHouseRentalID");

                    b.Property<int>("MemberItemID");

                    b.HasKey("Id");

                    b.HasIndex("BoatHouseRentalID");

                    b.HasIndex("MemberItemID");

                    b.ToTable("MemberItemInStorage");
                });

            modelBuilder.Entity("VaalBeachClub.Models.Domain.Members.MemberItemProperty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("MemberItemPropertyID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ItemPropertyID");

                    b.Property<int>("MemberItemID");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false);

                    b.HasKey("Id");

                    b.HasIndex("ItemPropertyID");

                    b.HasIndex("MemberItemID");

                    b.ToTable("MemberItemProperties");
                });

            modelBuilder.Entity("VaalBeachClub.Models.Domain.Members.MemberProfileImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("MemberProfileImageID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BeachClubMemberID");

                    b.Property<DateTime>("DateLastUpdated");

                    b.Property<int>("FileID");

                    b.HasKey("Id");

                    b.HasIndex("BeachClubMemberID");

                    b.HasIndex("FileID");

                    b.ToTable("MemberProfileImages");
                });

            modelBuilder.Entity("VaalBeachClub.Models.Domain.Members.MemberRegistration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("MemberRegistrationID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BeachClubMemberID");

                    b.Property<DateTime>("DateRegistrationCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool>("HasBeenApproved");

                    b.Property<bool>("HasBeenPaid");

                    b.Property<bool>("HasBeenProcessed");

                    b.Property<bool>("HasReadTermsAndConditions");

                    b.HasKey("Id");

                    b.HasIndex("BeachClubMemberID");

                    b.ToTable("MemberRegistrations");
                });

            modelBuilder.Entity("VaalBeachClub.Models.Domain.Rentals.BoatHouseRental", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("BoatHouseRentalID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BeachClubMemberID");

                    b.Property<int>("BoatHouseID");

                    b.Property<DateTime>("EndDate");

                    b.Property<bool>("HasBeenPaid");

                    b.Property<DateTime>("StartDate");

                    b.HasKey("Id");

                    b.HasIndex("BeachClubMemberID");

                    b.HasIndex("BoatHouseID");

                    b.ToTable("BoatHouseRentals");
                });

            modelBuilder.Entity("VaalBeachClub.Web.Data.Identity.BeachClubMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("BeachClubMemberID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<DateTime>("DateOfBirth");

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("BeachClubMembers");
                });

            modelBuilder.Entity("VaalBeachClub.Web.Data.Identity.BeachClubMemberClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("BeachClubMemberClaimID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<int>("UserId")
                        .HasColumnName("BeachClubMemberID");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("BeachClubMemberClaims");
                });

            modelBuilder.Entity("VaalBeachClub.Web.Data.Identity.BeachClubMemberLogin", b =>
                {
                    b.Property<string>("LoginProvider");

                    b.Property<string>("ProviderKey");

                    b.Property<string>("ProviderDisplayName");

                    b.Property<int>("UserId")
                        .HasColumnName("BeachClubMemberID");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("BeachClubMemberLogins");
                });

            modelBuilder.Entity("VaalBeachClub.Web.Data.Identity.BeachClubMemberRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnName("BeachClubMemberID");

                    b.Property<int>("RoleId")
                        .HasColumnName("BeachClubRoleID");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("BeachClubMemberRoles");
                });

            modelBuilder.Entity("VaalBeachClub.Web.Data.Identity.BeachClubMemberToken", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnName("BeachClubMemberID");

                    b.Property<string>("LoginProvider");

                    b.Property<string>("Name");

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("BeachClubMemberTokens");
                });

            modelBuilder.Entity("VaalBeachClub.Web.Data.Identity.BeachClubRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("BeachClubRoleID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("BeachClubRoles");
                });

            modelBuilder.Entity("VaalBeachClub.Web.Data.Identity.BeachClubRoleClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("BeachClubRoleClaimID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<int>("RoleId")
                        .HasColumnName("BeachClubRoleID");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("BeachClubRoleClaims");
                });

            modelBuilder.Entity("VaalBeachClub.Models.Domain.Addresses.ComplexAddress", b =>
                {
                    b.HasBaseType("VaalBeachClub.Models.Domain.Addresses.Address");

                    b.Property<string>("ComplexName");

                    b.Property<string>("ComplexUnitNumber");

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("VaalBeachClub.Models.Domain.Addresses.POBoxAddress", b =>
                {
                    b.HasBaseType("VaalBeachClub.Models.Domain.Addresses.Address");

                    b.Property<string>("POBoxNumber");

                    b.HasDiscriminator().HasValue(0);
                });

            modelBuilder.Entity("VaalBeachClub.Models.Domain.Addresses.StreetAddress", b =>
                {
                    b.HasBaseType("VaalBeachClub.Models.Domain.Addresses.Address");

                    b.Property<string>("StreetName")
                        .HasColumnType("varchar(250)")
                        .HasMaxLength(250);

                    b.Property<string>("StreetNumber");

                    b.ToTable("StreetAddresses");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("VaalBeachClub.Models.Domain.Addresses.Address", b =>
                {
                    b.HasOne("VaalBeachClub.Web.Data.Identity.BeachClubMember", "BeachClubMember")
                        .WithMany("Addresses")
                        .HasForeignKey("BeachClubMemberID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("VaalBeachClub.Models.Domain.Common.Country", "aCountry")
                        .WithMany("Addresses")
                        .HasForeignKey("CountryID")
                        .HasConstraintName("FK_Addresses_Countries")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("VaalBeachClub.Models.Domain.BoatHouses.BoatHouse", b =>
                {
                    b.HasOne("VaalBeachClub.Models.Domain.BoatHouses.BoatHouseSize", "BoatHouseSize")
                        .WithMany("BoatHouses")
                        .HasForeignKey("BoatHouseSizeID")
                        .HasConstraintName("FK_BoatHouses_BoatHouseSizes")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("VaalBeachClub.Models.Domain.Bookings.CampSiteBooking", b =>
                {
                    b.HasOne("VaalBeachClub.Web.Data.Identity.BeachClubMember", "BeachClubMember")
                        .WithMany("CampSiteBookings")
                        .HasForeignKey("BeachClubMemberID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("VaalBeachClub.Models.Domain.CampSites.CampSite", "CampSite")
                        .WithMany("CampSiteBookings")
                        .HasForeignKey("CampSiteID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("VaalBeachClub.Models.Domain.Common.ContactDetail", b =>
                {
                    b.HasOne("VaalBeachClub.Web.Data.Identity.BeachClubMember", "BeachClubMember")
                        .WithMany("ContactDetails")
                        .HasForeignKey("BeachClubMemberID")
                        .HasConstraintName("FK_ContactDetails_BeachClubMembers")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("VaalBeachClub.Models.Domain.Common.ContactDetailType", "ContactDetailType")
                        .WithMany("ContactDetails")
                        .HasForeignKey("ContactDetailTypeID")
                        .HasConstraintName("FK_ContactDetails_ContactDetailTypes")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("VaalBeachClub.Models.Domain.Fees.BoatHouseCommissionFee", b =>
                {
                    b.HasOne("VaalBeachClub.Models.Domain.BoatHouses.BoatHouseSize", "BoatHouseSize")
                        .WithMany("BoatHouseCommissionFees")
                        .HasForeignKey("BoatHouseSizeID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("VaalBeachClub.Models.Domain.Fees.EntranceCommissionFee", b =>
                {
                    b.HasOne("VaalBeachClub.Models.Domain.Fees.BeachClubFeeStructure")
                        .WithMany("EntranceCommissionFees")
                        .HasForeignKey("BeachClubFeeStructureID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("VaalBeachClub.Models.Domain.Items.ItemProperty", b =>
                {
                    b.HasOne("VaalBeachClub.Models.Domain.Items.ItemPropertyDataType", "ItemPropertyDataType")
                        .WithMany("ItemProperties")
                        .HasForeignKey("ItemPropertyDataTypeID")
                        .HasConstraintName("FK_ItemProperties_ItemPropertyDataTypes")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("VaalBeachClub.Models.Domain.Items.ItemTypeHierarchy", b =>
                {
                    b.HasOne("VaalBeachClub.Models.Domain.Items.ItemType", "Parent")
                        .WithMany("ItemTypeHierarchy")
                        .HasForeignKey("ParentID")
                        .HasConstraintName("FK_ItemTypeHierarchy_ItemTypes")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("VaalBeachClub.Models.Domain.Items.ItemTypeProperty", b =>
                {
                    b.HasOne("VaalBeachClub.Models.Domain.Items.ItemType", "Item")
                        .WithMany("ItemTypeProperties")
                        .HasForeignKey("ItemID")
                        .HasConstraintName("FK_ItemTypeProperties_ItemTypes")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("VaalBeachClub.Models.Domain.Items.ItemProperty", "ItemProperty")
                        .WithMany("ItemTypeProperties")
                        .HasForeignKey("ItemPropertyID")
                        .HasConstraintName("FK_ItemTypeProperties_ItemProperties")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("VaalBeachClub.Models.Domain.Logging.ActivityLog", b =>
                {
                    b.HasOne("VaalBeachClub.Models.Domain.Logging.ActivityLogType", "ActivityLogType")
                        .WithMany()
                        .HasForeignKey("ActivityLogTypeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("VaalBeachClub.Web.Data.Identity.BeachClubMember", "BeachClubMember")
                        .WithMany()
                        .HasForeignKey("BeachClubMemberId");
                });

            modelBuilder.Entity("VaalBeachClub.Models.Domain.Logging.Log", b =>
                {
                    b.HasOne("VaalBeachClub.Web.Data.Identity.BeachClubMember", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId");
                });

            modelBuilder.Entity("VaalBeachClub.Models.Domain.Members.AffiliatedMember", b =>
                {
                    b.HasOne("VaalBeachClub.Models.Domain.Members.AffiliatedMemberType", "AffiliatedMemberType")
                        .WithMany("AffiliatedMembers")
                        .HasForeignKey("AffiliatedMemberTypeID")
                        .HasConstraintName("FK_AffiliatedMembers_AffiliatedMemberTypes")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("VaalBeachClub.Web.Data.Identity.BeachClubMember", "Member")
                        .WithMany("AffiliatedMembers")
                        .HasForeignKey("BeachClubMemberID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("VaalBeachClub.Models.Domain.Members.MemberItem", b =>
                {
                    b.HasOne("VaalBeachClub.Web.Data.Identity.BeachClubMember", "BeachClubMember")
                        .WithMany("MemberItems")
                        .HasForeignKey("BeachClubMemberID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("VaalBeachClub.Models.Domain.Items.ItemType", "Item")
                        .WithMany("MemberItems")
                        .HasForeignKey("ItemID")
                        .HasConstraintName("FK_MemberItems_ItemTypes")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("VaalBeachClub.Models.Domain.Members.MemberItemInStorage", b =>
                {
                    b.HasOne("VaalBeachClub.Models.Domain.Rentals.BoatHouseRental", "BoatHouseUseToStoreMemberItem")
                        .WithMany("MemberItemsInStorage")
                        .HasForeignKey("BoatHouseRentalID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("VaalBeachClub.Models.Domain.Members.MemberItem", "MemberItemBeingStored")
                        .WithMany("MemberItemsInStorage")
                        .HasForeignKey("MemberItemID")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("VaalBeachClub.Models.Domain.Members.MemberItemProperty", b =>
                {
                    b.HasOne("VaalBeachClub.Models.Domain.Items.ItemProperty", "ItemProperty")
                        .WithMany("MemberAssetProperties")
                        .HasForeignKey("ItemPropertyID")
                        .HasConstraintName("FK_MemberItemProperties_ItemProperties_1")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("VaalBeachClub.Models.Domain.Members.MemberItem", "MemberItem")
                        .WithMany("MemberAssetProperties")
                        .HasForeignKey("MemberItemID")
                        .HasConstraintName("FK_MemberItemProperties_MemberItems_1")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("VaalBeachClub.Models.Domain.Members.MemberProfileImage", b =>
                {
                    b.HasOne("VaalBeachClub.Web.Data.Identity.BeachClubMember", "BeachClubMember")
                        .WithMany("MemberProfileImages")
                        .HasForeignKey("BeachClubMemberID")
                        .HasConstraintName("FK_MemberProfileImages_BeachClubMembers")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("VaalBeachClub.Models.Domain.Files.File", "File")
                        .WithMany("MemberProfileImages")
                        .HasForeignKey("FileID")
                        .HasConstraintName("FK_MemberProfileImages_Files")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("VaalBeachClub.Models.Domain.Members.MemberRegistration", b =>
                {
                    b.HasOne("VaalBeachClub.Web.Data.Identity.BeachClubMember", "BeachClubMember")
                        .WithMany("MemberRegistrations")
                        .HasForeignKey("BeachClubMemberID")
                        .HasConstraintName("FK_MemberRegistrations_BeachClubMembers")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("VaalBeachClub.Models.Domain.Rentals.BoatHouseRental", b =>
                {
                    b.HasOne("VaalBeachClub.Web.Data.Identity.BeachClubMember", "BeachClubMember")
                        .WithMany("BoatHouseRentals")
                        .HasForeignKey("BeachClubMemberID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("VaalBeachClub.Models.Domain.BoatHouses.BoatHouse", "BoatHouse")
                        .WithMany("BoatHouseRentals")
                        .HasForeignKey("BoatHouseID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("VaalBeachClub.Web.Data.Identity.BeachClubMemberClaim", b =>
                {
                    b.HasOne("VaalBeachClub.Web.Data.Identity.BeachClubMember", "Member")
                        .WithMany("Claims")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("VaalBeachClub.Web.Data.Identity.BeachClubMemberLogin", b =>
                {
                    b.HasOne("VaalBeachClub.Web.Data.Identity.BeachClubMember", "Member")
                        .WithMany("Logins")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("VaalBeachClub.Web.Data.Identity.BeachClubMemberRole", b =>
                {
                    b.HasOne("VaalBeachClub.Web.Data.Identity.BeachClubRole", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("VaalBeachClub.Web.Data.Identity.BeachClubMember", "Member")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("VaalBeachClub.Web.Data.Identity.BeachClubMemberToken", b =>
                {
                    b.HasOne("VaalBeachClub.Web.Data.Identity.BeachClubMember", "Member")
                        .WithMany("Tokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("VaalBeachClub.Web.Data.Identity.BeachClubRoleClaim", b =>
                {
                    b.HasOne("VaalBeachClub.Web.Data.Identity.BeachClubRole", "Role")
                        .WithMany("RoleClaims")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
