//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
//
//     Produced by Entity Framework Visual Editor
//     https://github.com/msawczyn/EFDesigner
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Runtime.CompilerServices;

namespace VaalBeachClub.Web.Data.Identity
{
   public partial class BeachClubUserClaim : IdentityUserClaim<int>
   {
      partial void Init();

      /// <summary>
      /// Default constructor. Protected due to required properties, but present because EF needs it.
      /// </summary>
      protected BeachClubUserClaim()
      {
         Init();
      }

      /// <summary>
      /// Public constructor with required data
      /// </summary>
      /// <param name="_beachclubuser0"></param>
      public BeachClubUserClaim(VaalBeachClub.Web.Data.Identity.BeachClubUser _beachclubuser0)
      {
         if (_beachclubuser0 == null) throw new ArgumentNullException(nameof(_beachclubuser0));
         _beachclubuser0.Claims.Add(this);

         Init();
      }

      /// <summary>
      /// Static create function (for use in LINQ queries, etc.)
      /// </summary>
      /// <param name="_beachclubuser0"></param>
      public static BeachClubUserClaim Create(VaalBeachClub.Web.Data.Identity.BeachClubUser _beachclubuser0)
      {
         return new BeachClubUserClaim(_beachclubuser0);
      }

      /*************************************************************************
       * Persistent properties
       *************************************************************************/

      /// <summary>
      /// Identity, Required, Indexed
      /// </summary>
      [Key]
      [Required]
      public int Id { get; set; }

      /*************************************************************************
       * Persistent navigation properties
       *************************************************************************/

      public virtual VaalBeachClub.Web.Data.Identity.BeachClubUser User { get; set; }

   }
}

