//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
//
//     Produced by Entity Framework Visual Editor
//     https://github.com/msawczyn/EFDesigner
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Runtime.CompilerServices;

namespace VaalBeachClub.Web.Data.Identity
{
   public partial class BeachClubUserRole : IdentityUserRole<int>
   {
      partial void Init();

      /// <summary>
      /// Default constructor. Protected due to required properties, but present because EF needs it.
      /// </summary>
      protected BeachClubUserRole()
      {
         Init();
      }

      /// <summary>
      /// Public constructor with required data
      /// </summary>
      /// <param name="_beachclubuser0"></param>
      /// <param name="_beachclubrole1"></param>
      public BeachClubUserRole(VaalBeachClub.Web.Data.Identity.BeachClubUser _beachclubuser0, VaalBeachClub.Web.Data.Identity.BeachClubRole _beachclubrole1)
      {
         if (_beachclubuser0 == null) throw new ArgumentNullException(nameof(_beachclubuser0));
         _beachclubuser0.UserRoles.Add(this);

         if (_beachclubrole1 == null) throw new ArgumentNullException(nameof(_beachclubrole1));
         _beachclubrole1.UserRoles.Add(this);

         Init();
      }

      /// <summary>
      /// Static create function (for use in LINQ queries, etc.)
      /// </summary>
      /// <param name="_beachclubuser0"></param>
      /// <param name="_beachclubrole1"></param>
      public static BeachClubUserRole Create(VaalBeachClub.Web.Data.Identity.BeachClubUser _beachclubuser0, VaalBeachClub.Web.Data.Identity.BeachClubRole _beachclubrole1)
      {
         return new BeachClubUserRole(_beachclubuser0, _beachclubrole1);
      }

      /*************************************************************************
       * Persistent properties
       *************************************************************************/

      /// <summary>
      /// Identity, Required, Indexed
      /// </summary>
      [Key]
      [Required]
      public int Id { get; set; }

      /*************************************************************************
       * Persistent navigation properties
       *************************************************************************/

      public virtual VaalBeachClub.Web.Data.Identity.BeachClubUser User { get; set; }

      public virtual VaalBeachClub.Web.Data.Identity.BeachClubRole Role { get; set; }

   }
}

