//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
//
//     Produced by Entity Framework Visual Editor
//     https://github.com/msawczyn/EFDesigner
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Runtime.CompilerServices;

namespace VaalBeachClub.Models.Domain.BoatHouses
{
   public partial class BoatHouse : VaalBeachClub.CustomeModel.BaseEntity
   {
      partial void Init();

      /// <summary>
      /// Default constructor. Protected due to required properties, but present because EF needs it.
      /// </summary>
      protected BoatHouse(): base()
      {
         Init();
      }

      /// <summary>
      /// Public constructor with required data
      /// </summary>
      /// <param name="boathousenumber"></param>
      public BoatHouse(string boathousenumber)
      {
         if (string.IsNullOrEmpty(boathousenumber)) throw new ArgumentNullException(nameof(boathousenumber));
         BoatHouseNumber = boathousenumber;
         Init();
      }

      /// <summary>
      /// Static create function (for use in LINQ queries, etc.)
      /// </summary>
      /// <param name="boathousenumber"></param>
      public static BoatHouse Create(string boathousenumber)
      {
         return new BoatHouse(boathousenumber);
      }

      /*************************************************************************
       * Persistent properties
       *************************************************************************/

      /// <summary>
      /// Required
      /// </summary>
      [Required]
      public string BoatHouseNumber { get; set; }

   }
}

